// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PufOYma0nOEnVvPWlzC6h9OhpIKlweg',
    appId: '1:141233840643:web:a90020796c319d06dca436',
    messagingSenderId: '141233840643',
    projectId: 'fluttertypescriptcourse-758e9',
    authDomain: 'fluttertypescriptcourse-758e9.firebaseapp.com',
    storageBucket: 'fluttertypescriptcourse-758e9.appspot.com',
    measurementId: 'G-KQ2K5W2X7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJyRjOYvJ_js0IPHv8cBQXU_e1gG_wpDM',
    appId: '1:141233840643:android:f755feac097dbf03dca436',
    messagingSenderId: '141233840643',
    projectId: 'fluttertypescriptcourse-758e9',
    storageBucket: 'fluttertypescriptcourse-758e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAesDwc0bsYDpZ0IHtzqqPjvxuq4HNCeQM',
    appId: '1:141233840643:ios:60508fe6fc219964dca436',
    messagingSenderId: '141233840643',
    projectId: 'fluttertypescriptcourse-758e9',
    storageBucket: 'fluttertypescriptcourse-758e9.appspot.com',
    iosBundleId: 'com.example.flutterWorkshopTweetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAesDwc0bsYDpZ0IHtzqqPjvxuq4HNCeQM',
    appId: '1:141233840643:ios:60508fe6fc219964dca436',
    messagingSenderId: '141233840643',
    projectId: 'fluttertypescriptcourse-758e9',
    storageBucket: 'fluttertypescriptcourse-758e9.appspot.com',
    iosBundleId: 'com.example.flutterWorkshopTweetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6PufOYma0nOEnVvPWlzC6h9OhpIKlweg',
    appId: '1:141233840643:web:3c3a36b1e78c6957dca436',
    messagingSenderId: '141233840643',
    projectId: 'fluttertypescriptcourse-758e9',
    authDomain: 'fluttertypescriptcourse-758e9.firebaseapp.com',
    storageBucket: 'fluttertypescriptcourse-758e9.appspot.com',
    measurementId: 'G-59FDX3YE60',
  );

}